version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['./entrypoint.sh']
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
  db:
    build:
      context: server/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - .env
