version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock-portfolio:latest
    entrypoint: ['./entrypoint.sh']
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DB_HOST=db:5432
  db:
    build:
      context: server/db
      dockerfile: Dockerfile
    image: db:latest
    ports:
      - "5433:5432"
    env_file:
      - .env
